### ISSUE TITLE
pb whit ldap : LOG15_ERROR

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/grafana_ynh#18]
hi, 
grafana was working very well, but now i have this error : 

  Grafana / Server Error
  Sadly something went wrong
  Failed to sync user
  
  Check the Grafana server logs for the detailed error message.

```
t=2019-02-26T23:38:56+0100 lvl=info msg="LDAP initial bind failed, %v" logger=ldap LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
t=2019-02-26T23:38:56+0100 lvl=eror msg="Failed to sync user" logger=context error="LDAP Result Code 206 \"Empty password not allowed by the client\": ldap: empty password not allowed by the client"
```
no pb with other apps using ldap, 
netdata is ok. 
i tried to remove then reinstall, but i have the same issue.
```
 # yunohost -v
yunohost: 
  repo: stable
  version: 3.4.2.4
yunohost-admin: 
  repo: stable
  version: 3.4.2
moulinette: 
  repo: stable
  version: 3.4.2
ssowat: 
  repo: stable
  version: 3.4.2

# yunohost app info grafana
description: Tableaux de bords de supervision
license: Apache-2.0
name: Grafana
version: 1.2.0~ynh1
```
thx for your help ;)
